const { col2, col1, col3 } = require("./colors");

module.exports = {
    fullbgpattern: {
        // flex: 1,
        position: 'absolute',
        width: '100%',
        zIndex: -1,
        height: '100%',
        // resizeMode: 'repeat',
    },
    fullbg: {
        // flex: 1,
        backgroundColor: '#fff',
        // alignItems: 'center',
        zIndex: 1,
        // justifyContent: 'center',
        height: '100%',
    },
    logobig: {
        width: '70%',
        height: 280,
        // height: 200,
        resizeMode: 'contain',
        // backgroundColor: '#fff',
    },
    logotext: {
        fontSize: 17,
        fontWeight: '600',
        color: col2,
        width: 180,
        textAlign: 'center',
        // fontFamily: 'Poppins-Regular',
    },
    cont1: {
        // flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        height: '50%',
        width: '100%',
        // backgroundColor: 'green',
    },
    cont2: {
        height: '50%',
        width: '100%',
        backgroundColor: '#FFD51E',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 400,
        
    },
    cont4: {
        height: '100%',
        width: '100%',
        backgroundColor: '#FFD51E',
        borderRadius: 60,
        alignItems: 'center',
        justifyContent: 'center',
    },
    h1auth: {
        fontSize: 50,
        color: '#fff',
    },
    h2auth: {
        fontSize: 16,
        color: '#fff',
        textAlign: 'center',
        width: 200,
    },
    btn1: {
        fontSize: 20,
        color: col1,
        backgroundColor: 'white',
        padding: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
        margin: 5,
        width: '80%',
        textAlign: 'center',
    },
    btn2: {
        fontSize: 20,
        color: 'white',
        backgroundColor: 'col1',
        padding: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
        margin: 5,
        width: '80%',
        textAlign: 'center',
        borderWidth: 1,
        borderColor: 'white',
    },
    input: {
        height: 40,
        margin: 5,
        // borderWidth: 1,
        padding: 10,
        paddingHorizontal: 20,
        width: '80%',
        borderRadius: 20,
        // borderColor: col3,
        backgroundColor: '#111111',
        color: 'white',
        opacity: 0.4,
        fontWeight: '700',
    },
    scrollview:{
        // flex:1,
        width:'100%',
        height:'100%',
        flex:1,
    },
    backbtn:{
        position:'absolute',
        top:20,
        left:20,
        backgroundColor:col1,
        color:'white',
        borderRadius:40,
        width:40,
        height:40,
        textAlign:'center',
        textAlignVertical:'center',
        fontSize:30,
        fontWeight:'500',
        fontFamily:'sans-serif',
        zIndex:2,
        borderColor:'white',
        borderWidth:1,
    }
} 